const products = [
  {
    id: 1,
    name: "iPhone 14 Pro",
    price: 199.99,
    category: "electronica",
    image: "https://picsum.photos/300/200?random=1",
    description: "El último iPhone con chip A16 Bionic y cámara profesional",
  },
  {
    id: 2,
    name: "MacBook Air M2",
    price: 1299.99,
    category: "electronica",
    image: "https://picsum.photos/300/200?random=2",
    description: "Portátil ultraligero con chip M2 de Apple",
  },
  {
    id: 3,
    name: "Camiseta Premium",
    price: 29.99,
    category: "ropa",
    image: "https://picsum.photos/300/200?random=3",
    description: "Camiseta de algodón orgánico 100%",
  },
  {
    id: 4,
    name: "Jeans Denim",
    price: 79.99,
    category: "ropa",
    image: "https://picsum.photos/300/200?random=4",
    description: "Jeans de corte clásico y lavado vintage",
  },
  {
    id: 5,
    name: "Lámpara LED",
    price: 45.99,
    category: "hogar",
    image: "https://picsum.photos/300/200?random=5",
    description: "Lámpara LED regulable con control remoto",
  },
  {
    id: 6,
    name: "Cojín Decorativo",
    price: 19.99,
    category: "hogar",
    image: "https://picsum.photos/300/200?random=6",
    description: "Cojín suave con diseño moderno",
  },
  {
    id: 7,
    name: "JavaScript: The Good Parts",
    price: 24.99,
    category: "libros",
    image: "https://picsum.photos/300/200?random=7",
    description: "Libro esencial para aprender JavaScript",
  },
  {
    id: 8,
    name: "Clean Code",
    price: 32.99,
    category: "libros",
    image: "https://picsum.photos/300/200?random=8",
    description: "Guía para escribir código limpio y mantenible",
  },
  {
    id: 9,
    name: "AirPods Pro",
    price: 249.99,
    category: "electronica",
    image: "https://picsum.photos/300/200?random=9",
    description: "Auriculares inalámbricos con cancelación de ruido",
  },
  {
    id: 10,
    name: "Zapatillas Deportivas",
    price: 89.99,
    category: "ropa",
    image: "https://picsum.photos/300/200?random=10",
    description: "Zapatillas cómodas para running y deporte",
  },
];
